{% set version = "12.8.1" %}
{% set exists = "" %}  # [not (linux or win)]
{% set exists = "which" %}  # [linux]
{% set exists = "where" %}  # [win]

package:
  name: cuda-compiler
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 1
  noarch: generic

requirements:
  run:
    - __linux  # [linux]
    - __win    # [win]
    - c-compiler
    - cxx-compiler
    - cuda-cuobjdump 12.8.90
    - cuda-cuxxfilt 12.8.90
    - cuda-nvcc 12.8.93
    - cuda-nvprune 12.8.90

test:
  commands:
    - {{ exists }} cuobjdump
    - {{ exists }} cu++filt
    - {{ exists }} nvcc
    - {{ exists }} nvprune

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: A meta-package containing tools to start developing a CUDA application
  description: |
    A meta-package containing tools to start developing and compiling a
    basic CUDA application.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
